# Generated by Django 5.1.2 on 2024-10-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="Название привычки")),
                ("action", models.TextField(verbose_name="Действие")),
                (
                    "place",
                    models.TextField(blank=True, null=True, verbose_name="место"),
                ),
                ("time", models.TimeField(blank=True, null=True, verbose_name="время")),
                (
                    "is_nice",
                    models.BooleanField(
                        default=False, verbose_name="признак приятной привычки"
                    ),
                ),
                ("periodicity", models.IntegerField(default=1)),
                ("time_to_implement", models.IntegerField(default=120)),
                ("is_public", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="Название вознаграждения")),
            ],
            options={
                "verbose_name": "Вознаграждение",
                "verbose_name_plural": "Вознаграждения",
            },
        ),
    ]
