# Generated by Django 5.1.2 on 2024-10-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="send_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="дата начала отправки"
            ),
        ),
    ]
